version: "3.8"
services:
  sor:
    container_name: sor
    image: git.unix.dog/lio/sor
    networks:
      - caddy
    labels:
      caddy: sor.dog
      caddy.reverse_proxy: "{{upstreams 3000}}"
      com.centurylinklabs.watchtower.enable: true
  abisu:
    container_name: abisu
    image: git.unix.dog/lio/abisu
    networks:
      - caddy
    labels:
      caddy: abisu.net
      caddy.reverse_proxy: "{{upstreams 3000}}"
      com.centurylinklabs.watchtower.enable: true
  alex:
    container_name: alex
    image: git.unix.dog/lio/alex
    networks:
      - caddy
    labels:
      caddy: alx.rip
      caddy.reverse_proxy: "{{upstreams 3000}}"
      com.centurylinklabs.watchtower.enable: true
  crook:
    container_name: crook
    image: git.unix.dog/lio/crook
    networks:
      - caddy
    labels:
      caddy: bastard.ink
      caddy.reverse_proxy: "{{upstreams 3000}}"
      com.centurylinklabs.watchtower.enable: true

networks:
  caddy:
    external: true
