version: "3"

networks:
  caddy:
    external: true
  # gitea:
  #   external: false

services:
  server:
    image: gitea/gitea
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea-db.sql
      - GITEA_APP_INI=/data/app.ini
      # - GITEA_CUSTOM=/data
      - GITEA_WORK_DIR=/data
    restart: always
    networks:
      - caddy
    labels:
      caddy: git.lio.cat
      caddy.reverse_proxy: "{{upstreams 3000}}"
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    # depends_on:
    #   - db

  # db:
  #   image: postgres:14
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=gitea
  #     - POSTGRES_PASSWORD=gitea
  #     - POSTGRES_DB=gitea
  #   networks:
  #     - gitea
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
