version: "3.2"

services:
  db:
    image: postgres:alpine
    restart: always
    networks:
      - local
    volumes:
      - db:/var/lib/postresql/data
    env_file:
      - db.env

  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    networks:
      - local
      - caddy
    labels:
      caddy: cloud.musky.cat
      caddy.reverse_proxy: "{{upstreams 80}}"
      com.centurylinklabs.watchtower.enable: true
    env_file:
      - db.env
    depends_on:
      - db

  cron:
    image: nextcloud
    restart: always
    networks:
      - local
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  db:
  nextcloud:

networks:
  local:
    driver: custom
  caddy:
    external: true
