version: "3.2"

services:
  db:
    image: postgres:alpine
    restart: always
    hostname: nc-postgres
    networks:
      - next
    volumes:
      - db:/var/lib/postresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=NEXTCLOUD_MUSKY_CAT

  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    networks:
      - next
      - caddy
    labels:
      caddy: cloud.musky.cat, virtual.implant.cam
      caddy.reverse_proxy: "{{upstreams 80}}"
      com.centurylinklabs.watchtower.enable: true
    environment:
      - POSTGRES_HOST=nc-postgres
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=NEXTCLOUD_MUSKY_CAT
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_TRUSTED_DOMAINS="cloud.musky.cat virtual.implant.cam"
    depends_on:
      - db

  cron:
    image: nextcloud
    restart: always
    networks:
      - next
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  db:
  nextcloud:

networks:
  next:
    name: next
  caddy:
    external: true
